### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by B-Alica** [entrepreneur-interet-general/django-dsfr#11]
Hello,

Currently it is not possible to add a name to a button.
I suggest to add this possibility, thus the dictionary for the button would look like that :
```
BTN_SUBMIT = {
        "label": "Soumettre",
        "onclick": "",
        "type":"submit",
        "extra_classes": ".........",
        "name": ".........",
    }
```

Is it possible ? Should I make a pull request ?

Thank you !

**Comment by Ash-Crow** [comment]
It seems good to me

**Comment by Ash-Crow** [comment]
@B-Alica Do you still need it/want to make a pull request for it?

**Comment by B-Alica** [comment]
Yes.
In the button.html, just add : 
`name="{{ self.name | default:'' }}"`
just below the "type" line.

Like this : 
`<button
  class="fr-btn{% if self.extra_classes %} {{ self.extra_classes }}{% endif %}"
  onclick="{{ self.onclick }}"
  {% if self.is_disabled %}disabled{% endif %}
  type="{{ self.type | default:'submit' }}"
  name="{{ self.name | default:'' }}"
>
  {{ self.label }}
</button>`

For now in my projects I override button.html and replace it with this, but is it possible to add it directly in dsfr/button.html ?
