### ISSUE TITLE
Support all supported versions of Django

### ISSUE THREAD

**Issue by rik** [entrepreneur-interet-general/django-dsfr#14]
At the moment, Django 3.2.x and Django 4.0.x are supported by the Django project. It would be nice to be able to use django-dsfr with Django 4.0.x.

Happy to try and submit a PR but I'm not yet sure how to change `pyproject.toml` and the github action to make sure the CI tests both branches.

**Comment by Ash-Crow** [comment]
Hi, 

You are very welcome to submit a PR!

For the pyproject.toml, I'm not exactly sure (I haven't bumped major versions yet), but I think it goes as follows:
- add `  "Framework :: Django :: 4.0",` to the classifier section
- replace `Django = "^3.2.5"` with `Django = ">3.2.5" in the dependencies`

For the CI, apparently like this: https://github.com/revsys/django-tos/pull/50/files#diff-c0d9756ec1e666a5c4b1ab6fa27d5662156838384a67802e705e4de44d6ab119

**Comment by rik** [comment]
For the CI, I'm not sure the example you linked would work well with Poetry. Can you tell Poetry that you want a particular version of one of the dependency already expressed in pyproject.toml?

**Comment by Ash-Crow** [comment]
Maybe by adding a step that updates the django version after the poetry install?

**Comment by mjeammet** [comment]
Thanks for merging my PR @Ash-Crow. Everything seems to be working like a charm, both with Django 3.2.16 and 4.1.5 !
