### ISSUE TITLE
Il n'est pas possible de mettre un lien sur le composant Carte

### ISSUE THREAD

**Issue by SebastienReuiller** [entrepreneur-interet-general/django-dsfr#54]
En utilisant le tag  `dsfr_card,` le lien n'est pas dans le HTML généré.

Exemple d'utilisation :

`{% dsfr_card title=subblock.value.title description=subblock.value.description link=subblock.value.url image_url=img.url %}`

Dans le code généré, le href est vide : 
`<a href="" target="_self">`

**Comment by Ash-Crow** [comment]
Merci pour la correction !
