### ISSUE TITLE
Mise à jour du DSFR à v1.10.1 et documenter le processus de mise à jour pour les contribs

### ISSUE THREAD

**Issue by christophehenry** [entrepreneur-interet-general/django-dsfr#57]
La version actuelle du DSFR est 1.10.1. La version embarquée dans `django-dsfr` est 1.9.2 soit 3 versions de retard. Il serait bien aussi de documenter ce qu'il faut faire lors de la mise à jour d'une nouvelle version du DSFR. De ce que j'ai vu dans le code, il ne suffit pas de bouger le `dist` du DSFR dans [`dsfr/static/dsfr/dist`](https://github.com/entrepreneur-interet-general/django-dsfr/tree/main/dsfr/static/dsfr/dist). J'ai l'impression qu'il faut aussi [mettre les les hash d'intégrité](https://github.com/entrepreneur-interet-general/django-dsfr/blob/main/dsfr/constants.py) à jour et [faire tourner la commande `trim_dist`](https://github.com/entrepreneur-interet-general/django-dsfr/blob/main/dsfr/management/commands/trim_dist.py) ?

**Comment by Ash-Crow** [comment]
Bonjour,

J'entame une nouvelle mission pour la Suite numérique de Beta.gouv et la mise à jour de ce paquet fait maintenant officiellement partie de mes missions, je devrais donc pouvoir effectuer les mises à jour plus régulièrement.

Je vais aussi faire un script de mise à jour pour les automatiser.
