### ISSUE TITLE
Documenter ce qui n'est pas pris en charge dans le DSFR

### ISSUE THREAD

**Issue by christophehenry** [entrepreneur-interet-general/django-dsfr#58]
La documentation indique :

> Django-DSFR (partly) implements the [version 1.9.2 of the DSFR](https://www.systeme-de-design.gouv.fr/a-propos/versions-du-dsfr/version-courante).

Il ne me semble pas que ce qui n'est pas implémenté soit documenté.

**Comment by Ash-Crow** [comment]
C'est dans l'onglet "Composants encore non implémentés" de la page https://entrepreneur-interet-general.github.io/django-dsfr/tags/

**Comment by christophehenry** [comment]
À moins que je me trompe, ce site n'est pas listé dans le README, ce qui explique que je ne l'ai pas trouvé.
