### ISSUE TITLE
Forms

### ISSUE THREAD

**Issue by B-Alica** [entrepreneur-interet-general/django-dsfr#8]
Hello,

I had to make forms with django-dsfr and I encountered several difficulties to make them. Indeed {{ form.as_p }} didn't render the form with the dsfr, and {% dsfr_input ... %} meant that we had to create each field separately without using a form class in forms.py.

I worked on a form_base.html file that could be useful to everyone to work more easily on forms with django-dsfr. It is a file that extends your base.html and is used by extending it in your form templates.
This file require a dependency : widget-tweaks. I suggest that it is added in django-dsfr.
I have also modified the widget templates : checkbox_option.html, input_option.html, multiple_input.html and radio_option.html.

Using these, it is possible to create a form class in forms.py, use it in a view class, and your form template would just look like this : 
```{% extends 'form-base.html' %}
{% load static dsfr_tags %}

{% block head-form %}
    <h2>Test de formulaire</h2>
{% endblock head-form %}

{% block foot-form %}
    {% dsfr_button btn_submit %}
{% endblock foot-form %}
```

Let me know if it's ok with you to pull a request ?
Thank you

**Comment by Ash-Crow** [comment]
Hi, sure, do not hesitate to make a PR!

**Comment by B-Alica** [comment]
Hello !
There is a problem with the PR from my contribution (form and formset).
form-base.html extends 'example_app/base.html'  ({% extends 'example_app/base.html' %}). But the user's base.html file may not be in an "example_app" app.
Is there a way to fix this ?

**Comment by Ash-Crow** [comment]
Yes, the user should not use a example_app. I'll look for the best way to fix this.

**Comment by B-Alica** [comment]
The easiest way is to replace {% extends 'example_app/base.html' %} with {% extends basetemplate %}
And then the user has to provide their base.html path to the context (context["basetemplate"] = "blabla/base.html")
But if the user doesn't provide the path, it won't work (error TemplateSyntaxError)

**Comment by B-Alica** [comment]
I made a new PR to correct the code duplication in the loops.

**Comment by Ash-Crow** [comment]
I changed the behavior a bit to make the form classes inherit of DsfrBaseForm instead of adding the fr-input class through widget_tweaks, which had unexpected side effect.

Everything should be good now
